import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future world",
  description: "Generated by create next app",
};

// This file is super important, it's the wrapper to display the whole app.
/* When we do build of our app (either for dev or production mode), the 
directory .next directory is created. If you have any issues, it could be due to the 
.next directory, cause it caches styles/components. So to solve the issues just 
delete the .next directory.
*/
// Reused component across the whole app goes in root layout. example navbar and footer.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              {/* Using Link allows us to reduce bandwidth cause it caches the files.
              Since Next.js renders on the server side we do less petitions 
              avoiding the reload (done with anchor <a>).
              And navigation is waymore fluid, since it doesn't reload.  
              Use link = internal app urls.
              Use anchor = for external url links ex.- google.com.
              */}
              <Link href={"/"}>
                <li>Home</li>
              </Link>

              <Link href={"/store"}>
                <li>Store</li>
              </Link>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
